spring.application.name=eureka

# Server Port
# Eureka's default port is 8761. It's a convention widely followed.
server.port=8761
# Eureka Server Configuration
# Should this server register itself with another Eureka server to form a cluster?
# Since this is a standalone server, we set this to false.
eureka.client.register-with-eureka=false
# Should this server fetch the registry from another Eureka server?
# Again, since it's the only server, it doesn't need to fetch a registry.
eureka.client.fetch-registry=false